# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: apps/tracks/grpc/tracks.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, '', 'apps/tracks/grpc/tracks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1d\x61pps/tracks/grpc/tracks.proto\x12\x06tracks\" \n\x0cTrackRequest\x12\x10\n\x08track_id\x18\x01 \x01(\t\"O\n\rTrackResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t2L\n\rTracksService\x12;\n\x0cGetTrackInfo\x12\x14.tracks.TrackRequest\x1a\x15.tracks.TrackResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apps.tracks.grpc.tracks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_TRACKREQUEST']._serialized_start = 41
    _globals['_TRACKREQUEST']._serialized_end = 73
    _globals['_TRACKRESPONSE']._serialized_start = 75
    _globals['_TRACKRESPONSE']._serialized_end = 154
    _globals['_TRACKSSERVICE']._serialized_start = 156
    _globals['_TRACKSSERVICE']._serialized_end = 232
# @@protoc_insertion_point(module_scope)
