# Generated by Django 4.2.30 on 2026-05-12 20:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content_type', models.CharField(choices=[('VIDEO', 'Vídeo'), ('ARTICLE', 'Artigo'), ('REPOSITORY', 'Repositório'), ('CHALLENGE', 'Desafio')], max_length=20)),
                ('content_url', models.URLField(blank=True, help_text='URL para VIDEO, ARTICLE ou REPOSITORY', null=True)),
                ('instructions', models.TextField(blank=True, help_text='Enunciado quando for um CHALLENGE', null=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Estimativa em minutos', null=True)),
                ('display_order', models.IntegerField(default=1, help_text='Ordem do conteúdo dentro do módulo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('display_order', models.IntegerField(default=1, help_text='Ordem do módulo dentro da trilha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creator_id', models.UUIDField(help_text='UUID do professor criador (resolvido via API de Auth)')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PUBLISHED', 'Publicado'), ('ARCHIVED', 'Arquivado')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(help_text='UUID do aluno (resolvido via API de Auth)')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Em Andamento'), ('COMPLETED', 'Concluído'), ('DROPPED', 'Desistente')], default='IN_PROGRESS', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='tracks.track')),
            ],
        ),
        migrations.CreateModel(
            name='UserModuleProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('IN_PROGRESS', 'Em Andamento'), ('COMPLETED', 'Concluído')], default='PENDING', max_length=20)),
                ('progress_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.module')),
                ('user_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='tracks.usertrack')),
            ],
        ),
        migrations.CreateModel(
            name='UserContentProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('COMPLETED', 'Concluído')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.content')),
                ('user_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_progress', to='tracks.usertrack')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='tracks.track'),
        ),
        migrations.AddField(
            model_name='content',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='tracks.module'),
        ),
        migrations.CreateModel(
            name='ChallengeSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_url', models.URLField(help_text='URL enviada pelo aluno')),
                ('ai_status', models.CharField(choices=[('PENDING_AI', 'Pendente IA'), ('EVALUATING', 'Em Avaliação'), ('EVALUATED', 'Avaliado'), ('FAILED', 'Falha na Avaliação')], default='PENDING_AI', max_length=20)),
                ('ai_feedback', models.TextField(blank=True, help_text='Feedback assíncrono consumido da fila', null=True)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, help_text='Preenchido pelo worker da IA ao finalizar', null=True)),
                ('challenge', models.ForeignKey(help_text='Deve apontar para um Content do tipo CHALLENGE', on_delete=django.db.models.deletion.CASCADE, to='tracks.content')),
                ('user_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tracks.usertrack')),
            ],
        ),
        migrations.AddConstraint(
            model_name='usertrack',
            constraint=models.UniqueConstraint(fields=('user_id', 'track'), name='unique_user_track_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='usermoduleprogress',
            constraint=models.UniqueConstraint(fields=('user_track', 'module'), name='unique_user_module_progress'),
        ),
        migrations.AddConstraint(
            model_name='usercontentprogress',
            constraint=models.UniqueConstraint(fields=('user_track', 'content'), name='unique_user_content_progress'),
        ),
    ]
