# Generated by Django 4.2.30 on 2026-05-12 02:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('duration_hours', models.IntegerField(help_text='Duração estimada do módulo em horas')),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suap_creator_id', models.CharField(help_text='ID do professor criador vindo da API do SUAP', max_length=225)),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PUBLISHED', 'Publicado'), ('ARCHIVED', 'Arquivado')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suap_user_id', models.CharField(help_text='Identificador do aluno via SUAP', max_length=255)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Em Andamento'), ('COMPLETED', 'Concluído'), ('DROPPED', 'Desistente')], default='IN_PROGRESS', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='tracks.track')),
            ],
        ),
        migrations.CreateModel(
            name='UserModuleProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('COMPLETED', 'Concluído')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.module')),
                ('user_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='tracks.usertrack')),
            ],
        ),
        migrations.CreateModel(
            name='TrackChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=225)),
                ('instructions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='tracks.track')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='tracks.track'),
        ),
        migrations.CreateModel(
            name='ChallengeSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_url', models.URLField(help_text='URL enviada pelo aluno')),
                ('ai_status', models.CharField(choices=[('PENDING_AI', 'Pendente IA'), ('EVALUATED', 'Avaliado')], default='PENDING_AI', max_length=20)),
                ('ai_feedback', models.TextField(blank=True, help_text='Feedback assíncrono consumido da fila', null=True)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.trackchallenge')),
                ('user_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tracks.usertrack')),
            ],
        ),
    ]
