# Generated by Django 4.2.30 on 2026-05-19 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengesubmission',
            old_name='challenge',
            new_name='content',
        ),
    ]
