# Generated by Django 4.2.30 on 2026-05-19 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_rename_challenge_challengesubmission_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengesubmission',
            old_name='content',
            new_name='challenge',
        ),
    ]
