# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, '', 'user.proto')
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nuser.proto\x12\x04user\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"T\n\x15ValidateTokenResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\" \n\x0bUserRequest\x12\x11\n\tmatricula\x18\x01 \x01(\t\"\x8b\x02\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tmatricula\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tfull_name\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\x0c\n\x04role\x18\x06 \x01(\t\x12\x0b\n\x03ira\x18\x07 \x01(\x02\x12\x0e\n\x06period\x18\x08 \x01(\x05\x12\x10\n\x08\x61\x62out_me\x18\t \x01(\t\x12\x10\n\x08linkedin\x18\n \x01(\t\x12\x0e\n\x06github\x18\x0b \x01(\t\x12\x18\n\x10\x63urriculo_lattes\x18\x0c \x01(\t\x12\x13\n\x0b\x63ourse_name\x18\r \x01(\t\x12\x18\n\x10institution_name\x18\x0e \x01(\t2W\n\x0b\x41uthService\x12H\n\rValidateToken\x12\x1a.user.ValidateTokenRequest\x1a\x1b.user.ValidateTokenResponse2F\n\x0bUserService\x12\x37\n\x0eGetUserProfile\x12\x11.user.UserRequest\x1a\x12.user.UserResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_VALIDATETOKENREQUEST']._serialized_start = 20
    _globals['_VALIDATETOKENREQUEST']._serialized_end = 57
    _globals['_VALIDATETOKENRESPONSE']._serialized_start = 59
    _globals['_VALIDATETOKENRESPONSE']._serialized_end = 143
    _globals['_USERREQUEST']._serialized_start = 145
    _globals['_USERREQUEST']._serialized_end = 177
    _globals['_USERRESPONSE']._serialized_start = 180
    _globals['_USERRESPONSE']._serialized_end = 447
    _globals['_AUTHSERVICE']._serialized_start = 449
    _globals['_AUTHSERVICE']._serialized_end = 536
    _globals['_USERSERVICE']._serialized_start = 538
    _globals['_USERSERVICE']._serialized_end = 608
# @@protoc_insertion_point(module_scope)
